# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170531_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.TextField(max_length=128, unique=True),
        ),
    ]
