# Generated by Django 2.0.6 on 2018-07-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20180611_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='distance_high',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='distance_low',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='distance_middle',
        ),
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='unit',
            field=models.CharField(choices=[('km', 'Километры'), ('m', 'Минуты')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.DurationField(blank=True, default=0.0),
        ),
    ]
