# Generated by Django 2.0.6 on 2018-07-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20180704_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='unit',
            field=models.CharField(choices=[('km', 'Километры'), ('m', 'Минуты')], default='km', max_length=4),
        ),
    ]
