# Generated by Django 2.0.6 on 2018-07-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20180704_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, default=0.0)),
                ('duration', models.DurationField(blank=True, default=0.0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.ExerciseType')),
            ],
        ),
        migrations.CreateModel(
            name='MonthPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My training plan', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='monthplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.TrainingPlan'),
        ),
    ]
