# Generated by Django 2.0.6 on 2018-07-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_trainingplan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='month_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='diary.MonthPlan'),
        ),
    ]
