# Generated by Django 2.0.6 on 2018-07-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_exerciseplan_month_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'permissions': {('view', 'Can see available Exercise Types')}},
        ),
    ]
